stages:
  prepare_data:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw/crop_yield.csv
      - src/data/make_dataset.py
    params:
      - prepare.test_size
      - prepare.random_state
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/features/build_features.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - src/models/train_model.py
    params:
      - train.algorithm
      - train.n_estimators
      - train.random_state
    outs:
      - models/model.pkl
    metrics:
      - metrics/train_metrics.json:
          cache: false

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/model.pkl
      - src/models/evaluate_model.py
    metrics:
      - metrics/test_metrics.json:
          cache: false